"""Rename timestamp fields

Revision ID: d72f5539fe2c
Revises: 9082aa0b3338
Create Date: 2024-10-17 09:29:00.617976

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d72f5539fe2c"
down_revision: str | None = "9082aa0b3338"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.add_column(
        "users",
        sa.Column("last_updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.drop_column("users", "created_on")
    op.drop_column("users", "last_updated_on")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "last_updated_on",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "last_updated_at")
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
