services:
  web:
    build: .
    image: eventtrakka-backend:latest
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8082
    volumes:
      - "/eventtrakka-backend/.venv"
      - ".:/eventtrakka-backend/"
    ports:
      - "8082:8082"
    env_file:
      - ./.env
    depends_on:
      - database
    restart: on-failure

  database:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - eventtrakka-db-volume:/var/lib/postgresql/data

volumes:
  eventtrakka-db-volume:
